name: upload-docs

on:
  push:
    branches:
      - "master"

env:
  PYTHON_VERSION: "3.10.10"
  PUBLISH_DIR: "./docs/api"
  PUBLISH_BRANCH: "gh-pages"
  DESTINATION_DIR: "api"

jobs:
  upload-doc:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: pip

      - name: Install libraries for ubuntu
        run: sudo apt-get install libsndfile1

      - name: Install Python dependencies
        shell: bash
        run: |
          pip install -r requirements.txt

      - name: Make documents
        shell: bash
        run: |
          python make_docs.py

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.PUBLISH_DIR }}
          publish_branch: ${{ env.PUBLISH_BRANCH }}
          destination_dir: ${{ env.DESTINATION_DIR }}
